name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Run the Maven Build
        run: cd PycraftServer && mvn --batch-mode --update-snapshots package
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: PycraftServer/target/PycraftServer*.jar
