name: Build and Release Plugin

on:
  push:
    tags:
      - "v-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Run the Maven Build
        run: cd PycraftServer && mvn --batch-mode --update-snapshots package
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "PycraftServer/target/PycraftServer*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
